### ISSUE TITLE
Crash when adding trim

### ISSUE THREAD

**Issue by mads10000** [jwa107/Photoshop-Export-Layers-to-Files-Fast#43]
Hi Guys

Script work well WITHOUT trim. I'm just in that situation a have 500 images that needs to be trimmed for making clickable surface buttons in an application. 

I work on Photoshop CS6 (OSX Yosemite 10.10.2)

I get this error when i add trim. What can i do?

Error: General Photoshop error occurred. This functionality may not be available in this version of Photoshop.
- Could not complete the command because of a program error.: on line 374

Here i have attached som images of my process..

Thanks you in advance.

![screen shot 2015-04-27 at 14 34 28](https://cloud.githubusercontent.com/assets/7805561/7347622/98e38400-ecea-11e4-96c2-6bbce11c312f.png)
![screen shot 2015-04-27 at 14 30 55](https://cloud.githubusercontent.com/assets/7805561/7347620/98c51664-ecea-11e4-99be-1bd842fbbdc7.png)
![screen shot 2015-04-27 at 14 31 09](https://cloud.githubusercontent.com/assets/7805561/7347621/98e2da5a-ecea-11e4-93e9-48983d3cca0e.png)

Second time i run the script with same adjustment as above these two error come:

![screen shot 2015-04-27 at 14 45 33](https://cloud.githubusercontent.com/assets/7805561/7347787/328bc120-ecec-11e4-813d-4002fcc657aa.png)
![screen shot 2015-04-27 at 14 45 39](https://cloud.githubusercontent.com/assets/7805561/7347786/326b6f60-ecec-11e4-8fa8-8df9f3154025.png)

**Comment by skjorn** [comment]
You have empty layers in your document, don't you? I fixed it, so it should be ok now. Update.

**Comment by mads10000** [comment]
Still crashes, not really any difference. I tried this time with CS5 on OSX 10.8.5

![screen shot 2015-04-29 at 9 38 19 pm](https://cloud.githubusercontent.com/assets/7805561/7399756/367bca8c-eeb8-11e4-8083-8eedbe8ab9c0.png)
![screen shot 2015-04-29 at 9 36 44 pm](https://cloud.githubusercontent.com/assets/7805561/7399755/367af7a6-eeb8-11e4-8dad-1b6dad213d3d.png)
![screen shot 2015-04-29 at 9 36 33 pm](https://cloud.githubusercontent.com/assets/7805561/7399757/367db81a-eeb8-11e4-95c1-a7e85a120c9d.png)

**Comment by skjorn** [comment]
Could you send me your PSD, please? Just post the link here if you can. (Or something else that crashes.)

**Comment by mads10000** [comment]
Yes here you go. Hope you can crack the issue.
http://we.tl/3I3byugI1d
Thanks for quick reply.

Cheers.

**Comment by mads10000** [comment]
Would just be great to have a solution that could export all layers (also in groups within groups) to trimmed single png's.

I got it to work i Photoshops own "save layers to file" script, if you remove all groups and only have layers. But anyone that makes any bigger(serious)(50+layers) projects needs to make groups to keep track of where all your stuff is. So don't understand why there is not a decent solution to this. Hope some of you guys can give me a tip/hint.

Cheers.

**Comment by skjorn** [comment]
"a solution that could export all layers [...] to trimmed single png's"
I don't think I follow. What do you mean?

"I cannot believe this can be close to impossible. I think the amount of user on photshop and the budget + talent available to adobes staff should be able to fix this little tweak"
It's not impossible, although not exactly a little tweak, they just don't care enough. They can't make a decent "layers to files" script for years; why would they bother about this?

**Comment by skjorn** [comment]
Works fine in CS 6 on Win 7. Looks like another mysterious Mac OS X issue. Cracked version? I guess we'll never know. I've done one thing I can do with it and that's pretty much it, even if I could reproduce the problem. Please try and let me know.

**Comment by mads10000** [comment]
#1 Each layer exported into a trimmed png.

#2 
Because every things made i photoshop related to app, website designs end up at a programmer as trimmed png's.

Am i wrong?

**Comment by mads10000** [comment]
ok

**Comment by skjorn** [comment]
#1 That's what this script does, doesn't it? Even the built-in PS script can trim when exporting to PNGs if I remember correctly. (Aside from organizing them into folders.)

**Comment by skjorn** [comment]
If the crack is bad, it may overwrite wrong places in memory and disrupt the original functionality. Basically throwing nonsense errors anywhere in the app. And your problem sounds exactly like an internal bad memory management issue. But it may be just poor QA testing from the Adobe. Everything's possible.
